// F3 全界面配色预设：8 套系统预制方案（warm / ink / sage / violet / ocean / peach / moon / pure）。
//
// 设计依据（doc/UI-Optimization设计文档.md §3.5）：
//   - 运行时 body 上有 350 个 --dsw-* 变量，其中 alias 语义层 78 个是组件
//     消费主力；覆盖 alias 层 = 全界面换色且语义一致；
//   - 每套 preset 只覆盖「决定风格」的语义面（底色族/文字族/品牌族/按钮族/
//     交互 hover/功能态 business/markdown/工具提示），state-error/success/warn
//     与 border 族保持官方（识别度 + 在任何底色上都成立）；
//   - 一致性规则：各层同色相派生；品牌色单点取材；文字层级同相递减；
//     允许撞色（品牌强调与底色为互补色相，如紫×琥珀、蓝×珊瑚橙）。
//
// 值以官方亮/暗基板为参照手工精调；helper 编译成与 F2 相同的
// `body { --dsw-*: … !important }` 注入块（theme.js 消费本文件）。

/** 三套预设；id 'default' 表示不覆盖（官方默认）。 */
export const PRESETS = {
  warm: {
    label: '暖木',
    desc: '暖米底色 + 琥珀焦橙强调，偏温和的阅读氛围。',
    chips: ['#f3e7d3', '#c2410c', '#2e261c'],
    light: {
      '--dsw-alias-bg-base': '#fdf6ee',
      '--dsw-alias-bg-layer-1': '#faf0e3',
      '--dsw-specific-input-major': '#faf0e3',
      '--dsw-alias-bg-layer-2': '#f5e9d6',
      '--dsw-alias-bg-layer-3': '#f0e1c9',
      '--dsw-alias-bg-module-platform': '#f3e7d3',
      '--dsw-specific-sidebar-fill': '#f3e7d3',
      '--dsw-alias-bg-overlay': '#e7d6ba',
      '--dsw-alias-bg-multi-select': '#f5e9d6',
      '--dsw-alias-label-primary': '#26201a',
      '--dsw-alias-label-secondary': '#6d6155',
      '--dsw-alias-label-tertiary': '#8f8273',
      '--dsw-alias-label-caption': '#ab9d8d',
      '--dsw-alias-brand-primary': '#c2410c',
      '--dsw-alias-brand-text': '#c2410c',
      '--dsw-alias-button-primary-fill': '#c2410c',
      '--dsw-alias-button-primary-hover': '#9a3412',
      '--dsw-alias-button-primary-dimmed': '#faddc3',
      '--dsw-alias-button-contrast-fill': '#26201a',
      '--dsw-alias-state-business-primary': '#c2410c',
      '--dsw-alias-state-business-tertiary': '#fae6d2',
      '--dsw-alias-interactive-bg-hover': '#c2410c14',
      '--dsw-alias-interactive-bg-active': '#c2410c1f',
      '--dsw-alias-interactive-bg-hover-solid': '#f5e9d6',
      '--dsw-alias-markdown-code-block': '#faf0e3',
      '--dsw-alias-markdown-code-block-banner': '#faf0e3',
      '--dsw-alias-markdown-inline-code': '#f4e7d3',
      '--dsw-alias-tooltip-bg': '#3a3027',
    },
    dark: {
      '--dsw-alias-bg-base': '#201a14',
      '--dsw-alias-bg-layer-1': '#2a221a',
      '--dsw-specific-input-major': '#2a221a',
      '--dsw-alias-bg-layer-2': '#332a20',
      '--dsw-alias-bg-layer-3': '#3c3125',
      '--dsw-alias-bg-module-platform': '#2e261c',
      '--dsw-specific-sidebar-fill': '#2e261c',
      '--dsw-alias-bg-overlay': '#45382b',
      '--dsw-alias-bg-multi-select': '#2a221a',
      '--dsw-alias-label-primary': '#f5efe6',
      '--dsw-alias-label-secondary': '#c9bda8',
      '--dsw-alias-label-tertiary': '#9f9180',
      '--dsw-alias-label-caption': '#857868',
      '--dsw-alias-brand-primary': '#fb923c',
      '--dsw-alias-brand-text': '#fb923c',
      '--dsw-alias-button-primary-fill': '#fb923c',
      '--dsw-alias-button-primary-hover': '#f59e0b',
      '--dsw-alias-button-primary-dimmed': '#4a2f1b',
      '--dsw-alias-button-contrast-fill': '#f5efe6',
      '--dsw-alias-state-business-primary': '#fb923c',
      '--dsw-alias-state-business-tertiary': '#3b2b1c',
      '--dsw-alias-interactive-bg-hover': '#fb923c26',
      '--dsw-alias-interactive-bg-active': '#fb923c33',
      '--dsw-alias-interactive-bg-hover-solid': '#2a221a',
      '--dsw-alias-markdown-code-block': '#2a221a',
      '--dsw-alias-markdown-code-block-banner': '#2a221a',
      '--dsw-alias-markdown-inline-code': '#362c21',
      '--dsw-alias-tooltip-bg': '#4a3f35',
    },
  },
  ink: {
    label: '石墨',
    desc: '低饱和冷灰底色 + 蓝青强调，冷静克制的工具风格。',
    chips: ['#e9edf1', '#2563eb', '#282d33'],
    light: {
      '--dsw-alias-bg-base': '#f4f6f8',
      '--dsw-alias-bg-layer-1': '#eef1f4',
      '--dsw-specific-input-major': '#eef1f4',
      '--dsw-alias-bg-layer-2': '#e8ecf0',
      '--dsw-alias-bg-layer-3': '#e2e7ec',
      '--dsw-alias-bg-module-platform': '#e9edf1',
      '--dsw-specific-sidebar-fill': '#e9edf1',
      '--dsw-alias-bg-overlay': '#d7dee5',
      '--dsw-alias-bg-multi-select': '#e8ecf0',
      '--dsw-alias-label-primary': '#191d21',
      '--dsw-alias-label-secondary': '#5a636d',
      '--dsw-alias-label-tertiary': '#7d8792',
      '--dsw-alias-label-caption': '#9aa3ad',
      '--dsw-alias-brand-primary': '#2563eb',
      '--dsw-alias-brand-text': '#2563eb',
      '--dsw-alias-button-primary-fill': '#2563eb',
      '--dsw-alias-button-primary-hover': '#1d4ed8',
      '--dsw-alias-button-primary-dimmed': '#dbe6fe',
      '--dsw-alias-button-contrast-fill': '#191d21',
      '--dsw-alias-state-business-primary': '#2563eb',
      '--dsw-alias-state-business-tertiary': '#e0e9fe',
      '--dsw-alias-interactive-bg-hover': '#2563eb14',
      '--dsw-alias-interactive-bg-active': '#2563eb1f',
      '--dsw-alias-interactive-bg-hover-solid': '#e8ecf0',
      '--dsw-alias-markdown-code-block': '#eef1f4',
      '--dsw-alias-markdown-code-block-banner': '#eef1f4',
      '--dsw-alias-markdown-inline-code': '#e3e9f2',
      '--dsw-alias-tooltip-bg': '#2f363e',
    },
    dark: {
      '--dsw-alias-bg-base': '#14171a',
      '--dsw-alias-bg-layer-1': '#1d2126',
      '--dsw-specific-input-major': '#1d2126',
      '--dsw-alias-bg-layer-2': '#262b31',
      '--dsw-alias-bg-layer-3': '#2f343b',
      '--dsw-alias-bg-module-platform': '#282d33',
      '--dsw-specific-sidebar-fill': '#282d33',
      '--dsw-alias-bg-overlay': '#363c44',
      '--dsw-alias-bg-multi-select': '#1d2126',
      '--dsw-alias-label-primary': '#eef1f4',
      '--dsw-alias-label-secondary': '#b9c1ca',
      '--dsw-alias-label-tertiary': '#8b96a1',
      '--dsw-alias-label-caption': '#77818c',
      '--dsw-alias-brand-primary': '#60a5fa',
      '--dsw-alias-brand-text': '#60a5fa',
      '--dsw-alias-button-primary-fill': '#60a5fa',
      '--dsw-alias-button-primary-hover': '#3b82f6',
      '--dsw-alias-button-primary-dimmed': '#1e3a5f',
      '--dsw-alias-button-contrast-fill': '#eef1f4',
      '--dsw-alias-state-business-primary': '#60a5fa',
      '--dsw-alias-state-business-tertiary': '#22334d',
      '--dsw-alias-interactive-bg-hover': '#60a5fa26',
      '--dsw-alias-interactive-bg-active': '#60a5fa33',
      '--dsw-alias-interactive-bg-hover-solid': '#1d2126',
      '--dsw-alias-markdown-code-block': '#1d2126',
      '--dsw-alias-markdown-code-block-banner': '#1d2126',
      '--dsw-alias-markdown-inline-code': '#252b31',
      '--dsw-alias-tooltip-bg': '#3a4249',
    },
  },
  sage: {
    label: '苔绿',
    desc: '米灰偏绿底色 + 深绿强调，自然柔和的低刺激配色。',
    chips: ['#eaeedf', '#2f855a', '#242c21'],
    light: {
      '--dsw-alias-bg-base': '#f6f8f4',
      '--dsw-alias-bg-layer-1': '#f0f3ec',
      '--dsw-specific-input-major': '#f0f3ec',
      '--dsw-alias-bg-layer-2': '#e8ecdf',
      '--dsw-alias-bg-layer-3': '#e0e6d3',
      '--dsw-alias-bg-module-platform': '#eaeedf',
      '--dsw-specific-sidebar-fill': '#eaeedf',
      '--dsw-alias-bg-overlay': '#d9e0ca',
      '--dsw-alias-bg-multi-select': '#e8ecdf',
      '--dsw-alias-label-primary': '#1f261c',
      '--dsw-alias-label-secondary': '#5f6857',
      '--dsw-alias-label-tertiary': '#818b78',
      '--dsw-alias-label-caption': '#9aa391',
      '--dsw-alias-brand-primary': '#2f855a',
      '--dsw-alias-brand-text': '#2f855a',
      '--dsw-alias-button-primary-fill': '#2f855a',
      '--dsw-alias-button-primary-hover': '#276749',
      '--dsw-alias-button-primary-dimmed': '#dcebde',
      '--dsw-alias-button-contrast-fill': '#1f261c',
      '--dsw-alias-state-business-primary': '#2f855a',
      '--dsw-alias-state-business-tertiary': '#e0ece1',
      '--dsw-alias-interactive-bg-hover': '#2f855a14',
      '--dsw-alias-interactive-bg-active': '#2f855a1f',
      '--dsw-alias-interactive-bg-hover-solid': '#e8ecdf',
      '--dsw-alias-markdown-code-block': '#f0f3ec',
      '--dsw-alias-markdown-code-block-banner': '#f0f3ec',
      '--dsw-alias-markdown-inline-code': '#e6ecdb',
      '--dsw-alias-tooltip-bg': '#2e372b',
    },
    dark: {
      '--dsw-alias-bg-base': '#121710',
      '--dsw-alias-bg-layer-1': '#1a2017',
      '--dsw-specific-input-major': '#1a2017',
      '--dsw-alias-bg-layer-2': '#222a1f',
      '--dsw-alias-bg-layer-3': '#2b3427',
      '--dsw-alias-bg-module-platform': '#242c21',
      '--dsw-specific-sidebar-fill': '#242c21',
      '--dsw-alias-bg-overlay': '#343d2f',
      '--dsw-alias-bg-multi-select': '#1a2017',
      '--dsw-alias-label-primary': '#eef2ea',
      '--dsw-alias-label-secondary': '#bdc6b2',
      '--dsw-alias-label-tertiary': '#929d85',
      '--dsw-alias-label-caption': '#7e8a72',
      '--dsw-alias-brand-primary': '#48bb78',
      '--dsw-alias-brand-text': '#48bb78',
      '--dsw-alias-button-primary-fill': '#48bb78',
      '--dsw-alias-button-primary-hover': '#34d399',
      '--dsw-alias-button-primary-dimmed': '#1c3627',
      '--dsw-alias-button-contrast-fill': '#eef2ea',
      '--dsw-alias-state-business-primary': '#48bb78',
      '--dsw-alias-state-business-tertiary': '#213527',
      '--dsw-alias-interactive-bg-hover': '#48bb7826',
      '--dsw-alias-interactive-bg-active': '#48bb7833',
      '--dsw-alias-interactive-bg-hover-solid': '#1a2017',
      '--dsw-alias-markdown-code-block': '#1a2017',
      '--dsw-alias-markdown-code-block-banner': '#1a2017',
      '--dsw-alias-markdown-inline-code': '#222a1f',
      '--dsw-alias-tooltip-bg': '#39442f',
    },
  },
  violet: {
    label: '紫夜',
    desc: '淡紫底 + 琥珀金强调，紫金撞色的夜间氛围。',
    chips: ['#ece6f4', '#b45309', '#231d2e'],
    light: {
      '--dsw-alias-bg-base': '#f7f4fb',
      '--dsw-alias-bg-layer-1': '#f1ecf7',
      '--dsw-specific-input-major': '#f1ecf7',
      '--dsw-alias-bg-layer-2': '#e9e2f2',
      '--dsw-alias-bg-layer-3': '#e1d8ec',
      '--dsw-alias-bg-module-platform': '#ece6f4',
      '--dsw-specific-sidebar-fill': '#ece6f4',
      '--dsw-alias-bg-overlay': '#d5c9e2',
      '--dsw-alias-bg-multi-select': '#e9e2f2',
      '--dsw-alias-label-primary': '#231d2e',
      '--dsw-alias-label-secondary': '#5f5471',
      '--dsw-alias-label-tertiary': '#827493',
      '--dsw-alias-label-caption': '#a292b3',
      '--dsw-alias-brand-primary': '#b45309',
      '--dsw-alias-brand-text': '#b45309',
      '--dsw-alias-button-primary-fill': '#b45309',
      '--dsw-alias-button-primary-hover': '#92400e',
      '--dsw-alias-button-primary-dimmed': '#fbe7d0',
      '--dsw-alias-button-contrast-fill': '#231d2e',
      '--dsw-alias-state-business-primary': '#b45309',
      '--dsw-alias-state-business-tertiary': '#fdeed8',
      '--dsw-alias-interactive-bg-hover': '#b4530914',
      '--dsw-alias-interactive-bg-active': '#b453091f',
      '--dsw-alias-interactive-bg-hover-solid': '#e9e2f2',
      '--dsw-alias-markdown-code-block': '#f1ecf7',
      '--dsw-alias-markdown-code-block-banner': '#f1ecf7',
      '--dsw-alias-markdown-inline-code': '#ede6f4',
      '--dsw-alias-tooltip-bg': '#3b3347',
    },
    dark: {
      '--dsw-alias-bg-base': '#17131f',
      '--dsw-alias-bg-layer-1': '#1e1929',
      '--dsw-specific-input-major': '#1e1929',
      '--dsw-alias-bg-layer-2': '#272030',
      '--dsw-alias-bg-layer-3': '#30283a',
      '--dsw-alias-bg-module-platform': '#231d2e',
      '--dsw-specific-sidebar-fill': '#231d2e',
      '--dsw-alias-bg-overlay': '#38304a',
      '--dsw-alias-bg-multi-select': '#1e1929',
      '--dsw-alias-label-primary': '#f3eff9',
      '--dsw-alias-label-secondary': '#cfc6dc',
      '--dsw-alias-label-tertiary': '#a397b8',
      '--dsw-alias-label-caption': '#8d80a3',
      '--dsw-alias-brand-primary': '#fbbf24',
      '--dsw-alias-brand-text': '#fbbf24',
      '--dsw-alias-button-primary-fill': '#fbbf24',
      '--dsw-alias-button-primary-hover': '#f59e0b',
      '--dsw-alias-button-primary-dimmed': '#4a3414',
      '--dsw-alias-button-contrast-fill': '#f3eff9',
      '--dsw-alias-state-business-primary': '#fbbf24',
      '--dsw-alias-state-business-tertiary': '#453a1e',
      '--dsw-alias-interactive-bg-hover': '#fbbf2426',
      '--dsw-alias-interactive-bg-active': '#fbbf2433',
      '--dsw-alias-interactive-bg-hover-solid': '#1e1929',
      '--dsw-alias-markdown-code-block': '#1e1929',
      '--dsw-alias-markdown-code-block-banner': '#1e1929',
      '--dsw-alias-markdown-inline-code': '#262137',
      '--dsw-alias-tooltip-bg': '#463d55',
    },
  },
  ocean: {
    label: '碧海',
    desc: '深海蓝底 + 珊瑚橙强调，冷暖撞色清爽醒目。',
    chips: ['#e4edf4', '#ea580c', '#152636'],
    light: {
      '--dsw-alias-bg-base': '#f2f7fb',
      '--dsw-alias-bg-layer-1': '#e8f0f7',
      '--dsw-specific-input-major': '#e8f0f7',
      '--dsw-alias-bg-layer-2': '#dce7f0',
      '--dsw-alias-bg-layer-3': '#d1dfeb',
      '--dsw-alias-bg-module-platform': '#e4edf4',
      '--dsw-specific-sidebar-fill': '#e4edf4',
      '--dsw-alias-bg-overlay': '#c2d5e3',
      '--dsw-alias-bg-multi-select': '#dce7f0',
      '--dsw-alias-label-primary': '#12202e',
      '--dsw-alias-label-secondary': '#45586b',
      '--dsw-alias-label-tertiary': '#6b8195',
      '--dsw-alias-label-caption': '#8ba0b3',
      '--dsw-alias-brand-primary': '#ea580c',
      '--dsw-alias-brand-text': '#ea580c',
      '--dsw-alias-button-primary-fill': '#ea580c',
      '--dsw-alias-button-primary-hover': '#c2410c',
      '--dsw-alias-button-primary-dimmed': '#ffe4d1',
      '--dsw-alias-button-contrast-fill': '#12202e',
      '--dsw-alias-state-business-primary': '#ea580c',
      '--dsw-alias-state-business-tertiary': '#ffe8d8',
      '--dsw-alias-interactive-bg-hover': '#ea580c14',
      '--dsw-alias-interactive-bg-active': '#ea580c1f',
      '--dsw-alias-interactive-bg-hover-solid': '#dce7f0',
      '--dsw-alias-markdown-code-block': '#e8f0f7',
      '--dsw-alias-markdown-code-block-banner': '#e8f0f7',
      '--dsw-alias-markdown-inline-code': '#e2ebf3',
      '--dsw-alias-tooltip-bg': '#2a3a4d',
    },
    dark: {
      '--dsw-alias-bg-base': '#0c1826',
      '--dsw-alias-bg-layer-1': '#12202e',
      '--dsw-specific-input-major': '#12202e',
      '--dsw-alias-bg-layer-2': '#1a2b3d',
      '--dsw-alias-bg-layer-3': '#22364b',
      '--dsw-alias-bg-module-platform': '#152636',
      '--dsw-specific-sidebar-fill': '#152636',
      '--dsw-alias-bg-overlay': '#2b4158',
      '--dsw-alias-bg-multi-select': '#12202e',
      '--dsw-alias-label-primary': '#eef5fb',
      '--dsw-alias-label-secondary': '#b9cbd9',
      '--dsw-alias-label-tertiary': '#8ba2b7',
      '--dsw-alias-label-caption': '#748ba1',
      '--dsw-alias-brand-primary': '#fb923c',
      '--dsw-alias-brand-text': '#fb923c',
      '--dsw-alias-button-primary-fill': '#fb923c',
      '--dsw-alias-button-primary-hover': '#f97316',
      '--dsw-alias-button-primary-dimmed': '#4a2913',
      '--dsw-alias-button-contrast-fill': '#eef5fb',
      '--dsw-alias-state-business-primary': '#fb923c',
      '--dsw-alias-state-business-tertiary': '#3d2a17',
      '--dsw-alias-interactive-bg-hover': '#fb923c26',
      '--dsw-alias-interactive-bg-active': '#fb923c33',
      '--dsw-alias-interactive-bg-hover-solid': '#12202e',
      '--dsw-alias-markdown-code-block': '#12202e',
      '--dsw-alias-markdown-code-block-banner': '#12202e',
      '--dsw-alias-markdown-inline-code': '#1a2b3d',
      '--dsw-alias-tooltip-bg': '#3a4656',
    },
  },
  peach: {
    label: '蜜桃',
    desc: '暖粉米底 + 莓红强调，温柔活泼的甜系配色。',
    chips: ['#f8e8e4', '#be123c', '#2c1d1a'],
    light: {
      '--dsw-alias-bg-base': '#fdf6f4',
      '--dsw-alias-bg-layer-1': '#faece9',
      '--dsw-specific-input-major': '#faece9',
      '--dsw-alias-bg-layer-2': '#f5e0dc',
      '--dsw-alias-bg-layer-3': '#efd3ce',
      '--dsw-alias-bg-module-platform': '#f8e8e4',
      '--dsw-specific-sidebar-fill': '#f8e8e4',
      '--dsw-alias-bg-overlay': '#e8cbc4',
      '--dsw-alias-bg-multi-select': '#f5e0dc',
      '--dsw-alias-label-primary': '#33231f',
      '--dsw-alias-label-secondary': '#7a5d55',
      '--dsw-alias-label-tertiary': '#95786f',
      '--dsw-alias-label-caption': '#ad948c',
      '--dsw-alias-brand-primary': '#be123c',
      '--dsw-alias-brand-text': '#be123c',
      '--dsw-alias-button-primary-fill': '#be123c',
      '--dsw-alias-button-primary-hover': '#9f1239',
      '--dsw-alias-button-primary-dimmed': '#fde2e8',
      '--dsw-alias-button-contrast-fill': '#33231f',
      '--dsw-alias-state-business-primary': '#be123c',
      '--dsw-alias-state-business-tertiary': '#fce8ec',
      '--dsw-alias-interactive-bg-hover': '#be123c14',
      '--dsw-alias-interactive-bg-active': '#be123c1f',
      '--dsw-alias-interactive-bg-hover-solid': '#f5e0dc',
      '--dsw-alias-markdown-code-block': '#faece9',
      '--dsw-alias-markdown-code-block-banner': '#faece9',
      '--dsw-alias-markdown-inline-code': '#f7e6e3',
      '--dsw-alias-tooltip-bg': '#46302c',
    },
    dark: {
      '--dsw-alias-bg-base': '#1d1210',
      '--dsw-alias-bg-layer-1': '#281a17',
      '--dsw-specific-input-major': '#281a17',
      '--dsw-alias-bg-layer-2': '#332220',
      '--dsw-alias-bg-layer-3': '#3e2a27',
      '--dsw-alias-bg-module-platform': '#2c1d1a',
      '--dsw-specific-sidebar-fill': '#2c1d1a',
      '--dsw-alias-bg-overlay': '#4a332f',
      '--dsw-alias-bg-multi-select': '#281a17',
      '--dsw-alias-label-primary': '#fdf2f0',
      '--dsw-alias-label-secondary': '#d9bcb6',
      '--dsw-alias-label-tertiary': '#ab8d86',
      '--dsw-alias-label-caption': '#937a74',
      '--dsw-alias-brand-primary': '#fb7185',
      '--dsw-alias-brand-text': '#fb7185',
      '--dsw-alias-button-primary-fill': '#fb7185',
      '--dsw-alias-button-primary-hover': '#f43f5e',
      '--dsw-alias-button-primary-dimmed': '#4a2128',
      '--dsw-alias-button-contrast-fill': '#fdf2f0',
      '--dsw-alias-state-business-primary': '#fb7185',
      '--dsw-alias-state-business-tertiary': '#46242c',
      '--dsw-alias-interactive-bg-hover': '#fb718526',
      '--dsw-alias-interactive-bg-active': '#fb718533',
      '--dsw-alias-interactive-bg-hover-solid': '#281a17',
      '--dsw-alias-markdown-code-block': '#281a17',
      '--dsw-alias-markdown-code-block-banner': '#281a17',
      '--dsw-alias-markdown-inline-code': '#331f1c',
      '--dsw-alias-tooltip-bg': '#4d3631',
    },
  },
  moon: {
    label: '海月',
    desc: '沁蓝紫底 + 淡紫罗兰强调，月色冷调浪漫。',
    chips: ['#eedfd8', '#47499C', '#201f40'],
    light: {
      '--dsw-alias-bg-base': '#f6e3dc',
      '--dsw-alias-bg-layer-1': '#f1e0da',
      '--dsw-specific-input-major': '#f1e0da',
      '--dsw-alias-bg-layer-2': '#ead4cd',
      '--dsw-alias-bg-layer-3': '#e3c9c1',
      '--dsw-alias-bg-module-platform': '#eedfd8',
      '--dsw-specific-sidebar-fill': '#eedfd8',
      '--dsw-alias-bg-overlay': '#d7bab1',
      '--dsw-alias-bg-multi-select': '#ead4cd',
      '--dsw-alias-label-primary': '#2b2429',
      '--dsw-alias-label-secondary': '#78605c',
      '--dsw-alias-label-tertiary': '#96807c',
      '--dsw-alias-label-caption': '#ae9994',
      '--dsw-alias-brand-primary': '#47499C',
      '--dsw-alias-brand-text': '#47499C',
      '--dsw-alias-button-primary-fill': '#47499C',
      '--dsw-alias-button-primary-hover': '#2E2D69',
      '--dsw-alias-button-primary-dimmed': '#e8e6f6',
      '--dsw-alias-button-contrast-fill': '#2b2429',
      '--dsw-alias-state-business-primary': '#47499C',
      '--dsw-alias-state-business-tertiary': '#e9e7f6',
      '--dsw-alias-interactive-bg-hover': '#47499c14',
      '--dsw-alias-interactive-bg-active': '#47499c1f',
      '--dsw-alias-interactive-bg-hover-solid': '#ead4cd',
      '--dsw-alias-markdown-code-block': '#f1e0da',
      '--dsw-alias-markdown-code-block-banner': '#f1e0da',
      '--dsw-alias-markdown-inline-code': '#f3e2dc',
      '--dsw-alias-tooltip-bg': '#32315c',
    },
    dark: {
      '--dsw-alias-bg-base': '#15142e',
      '--dsw-alias-bg-layer-1': '#1c1b39',
      '--dsw-specific-input-major': '#1c1b39',
      '--dsw-alias-bg-layer-2': '#26254c',
      '--dsw-alias-bg-layer-3': '#2E2D69',
      '--dsw-alias-bg-module-platform': '#201f40',
      '--dsw-specific-sidebar-fill': '#201f40',
      '--dsw-alias-bg-overlay': '#3a3968',
      '--dsw-alias-bg-multi-select': '#1c1b39',
      '--dsw-alias-label-primary': '#f4f3fa',
      '--dsw-alias-label-secondary': '#c8c6de',
      '--dsw-alias-label-tertiary': '#9b99c0',
      '--dsw-alias-label-caption': '#8583ab',
      '--dsw-alias-brand-primary': '#8D8CC5',
      '--dsw-alias-brand-text': '#8D8CC5',
      '--dsw-alias-button-primary-fill': '#8D8CC5',
      '--dsw-alias-button-primary-hover': '#a5a4d4',
      '--dsw-alias-button-primary-dimmed': '#2e2c5c',
      '--dsw-alias-button-contrast-fill': '#f4f3fa',
      '--dsw-alias-state-business-primary': '#8D8CC5',
      '--dsw-alias-state-business-tertiary': '#2b2a56',
      '--dsw-alias-interactive-bg-hover': '#8d8cc526',
      '--dsw-alias-interactive-bg-active': '#8d8cc533',
      '--dsw-alias-interactive-bg-hover-solid': '#1c1b39',
      '--dsw-alias-markdown-code-block': '#1c1b39',
      '--dsw-alias-markdown-code-block-banner': '#1c1b39',
      '--dsw-alias-markdown-inline-code': '#242349',
      '--dsw-alias-tooltip-bg': '#47499C',
    },
  },
  pure: {
    label: '净华',
    desc: '雾灰底 + 苔绿强调，橄榄与暖沙的明净调。',
    chips: ['#e2dede', '#658874', '#1c1f16'],
    light: {
      '--dsw-alias-bg-base': '#ebe7e8',
      '--dsw-alias-bg-layer-1': '#e4e1e1',
      '--dsw-specific-input-major': '#e4e1e1',
      '--dsw-alias-bg-layer-2': '#dcd8d8',
      '--dsw-alias-bg-layer-3': '#d3cfce',
      '--dsw-alias-bg-module-platform': '#e2dede',
      '--dsw-specific-sidebar-fill': '#e2dede',
      '--dsw-alias-bg-overlay': '#d6bea6',
      '--dsw-alias-bg-multi-select': '#dcd8d8',
      '--dsw-alias-label-primary': '#292b23',
      '--dsw-alias-label-secondary': '#64695c',
      '--dsw-alias-label-tertiary': '#878c7e',
      '--dsw-alias-label-caption': '#a3a799',
      '--dsw-alias-brand-primary': '#658874',
      '--dsw-alias-brand-text': '#658874',
      '--dsw-alias-button-primary-fill': '#658874',
      '--dsw-alias-button-primary-hover': '#2D2F21',
      '--dsw-alias-button-primary-dimmed': '#e9eddd',
      '--dsw-alias-button-contrast-fill': '#292b23',
      '--dsw-alias-state-business-primary': '#658874',
      '--dsw-alias-state-business-tertiary': '#e6ead7',
      '--dsw-alias-interactive-bg-hover': '#65887414',
      '--dsw-alias-interactive-bg-active': '#6588741f',
      '--dsw-alias-interactive-bg-hover-solid': '#dcd8d8',
      '--dsw-alias-markdown-code-block': '#e4e1e1',
      '--dsw-alias-markdown-code-block-banner': '#e4e1e1',
      '--dsw-alias-markdown-inline-code': '#e6e1de',
      '--dsw-alias-tooltip-bg': '#33362a',
    },
    dark: {
      '--dsw-alias-bg-base': '#12140e',
      '--dsw-alias-bg-layer-1': '#191b14',
      '--dsw-specific-input-major': '#191b14',
      '--dsw-alias-bg-layer-2': '#20231a',
      '--dsw-alias-bg-layer-3': '#2D2F21',
      '--dsw-alias-bg-module-platform': '#1c1f16',
      '--dsw-specific-sidebar-fill': '#1c1f16',
      '--dsw-alias-bg-overlay': '#343829',
      '--dsw-alias-bg-multi-select': '#191b14',
      '--dsw-alias-label-primary': '#f2f1ec',
      '--dsw-alias-label-secondary': '#c6c8b9',
      '--dsw-alias-label-tertiary': '#9a9d8b',
      '--dsw-alias-label-caption': '#838676',
      '--dsw-alias-brand-primary': '#B9C88D',
      '--dsw-alias-brand-text': '#B9C88D',
      '--dsw-alias-button-primary-fill': '#B9C88D',
      '--dsw-alias-button-primary-hover': '#c6d4a0',
      '--dsw-alias-button-primary-dimmed': '#2f3a26',
      '--dsw-alias-button-contrast-fill': '#f2f1ec',
      '--dsw-alias-state-business-primary': '#B9C88D',
      '--dsw-alias-state-business-tertiary': '#2c3324',
      '--dsw-alias-interactive-bg-hover': '#B9c88d26',
      '--dsw-alias-interactive-bg-active': '#B9c88d33',
      '--dsw-alias-interactive-bg-hover-solid': '#191b14',
      '--dsw-alias-markdown-code-block': '#191b14',
      '--dsw-alias-markdown-code-block-banner': '#191b14',
      '--dsw-alias-markdown-inline-code': '#1f2318',
      '--dsw-alias-tooltip-bg': '#4a5340',
    },
  },
}

/** preset 选择元数据（default 表示不覆盖 = 官方默认）。 */
export const PRESET_IDS = ['default', 'warm', 'ink', 'sage', 'violet', 'ocean', 'peach', 'moon', 'pure']